booksnob/booksnob/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from reader.views import HomeView
from django.conf.urls.static import static
from booksnob import settings
from views import set_timezone

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^reader/', include('reader.urls')),
    url(r'^critic/', include('critic.urls')),
    url(r'timezone/$', set_timezone),
    url(r'^api-auth/', include('djangorestapitutorial.urls',
                               namespace='djangorestapitutorial')),
    url(r'^docs/', include('rest_framework_swagger.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

booksnob/critic/urls.py
from django.conf.urls import url
from critic.views import ReviewView, ThanksView


urlpatterns = [
    url(r'^review/$', ReviewView.as_view(), name='review-book'),
    url(r'^thanks/$', ThanksView.as_view(), name='thanks'),
]

booksnob/reader/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import cache_page
from views import AuthorView, GetAuthorView, GetAuthorList, RegisterFormView, \
    AutheticationForm, LogoutForm


urlpatterns = [

    url(r'^get_auth/$', login_required(AuthorView.as_view()),
        name='get_author'),
    url(r'^get_auth/(?P<pk>\d+)/$', login_required(GetAuthorView.as_view()),
        name='auth_by_id'),
    url(r'^get_auth/all/$',
        cache_page(60 * 60)(login_required(GetAuthorList.as_view())),
        name='get_author_all'),
    url(r'^register/$', RegisterFormView.as_view(), name='register'),
    url(r'^login/$', AutheticationForm.as_view(), name='login'),
    url(r'^logout/$', login_required(LogoutForm.as_view()), name='logout')
]

booksnob/reader/models.py
import datetime
from django.db import models
from reader.managers import AuthorManager
from django.db.models.signals import post_save
from django.dispatch import receiver


class Author(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=40)
    avatar = models.ImageField(upload_to="static/reader",
                               default="static/default_avatar.png")
    email = models.EmailField()
    filter_author = AuthorManager()
    objects = models.Manager()

    def __unicode__(self):
        return '{0} {1} {2}'.format(self.first_name, self.last_name, self.email)


class AuthorSubmitDate(models.Model):
    author = models.OneToOneField(Author)
    date = models.DateTimeField()


class Book(models.Model):
    author = models.ForeignKey(Author)
    name = models.CharField(max_length=100)

    def __unicode__(self):
        return str(self.name)


class Reader(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    age = models.IntegerField()
    reader = models.ManyToManyField(Book)

    def __unicode__(self):
        return str(
            '{0} {1},{2}'.format(self.first_name, self.last_name, self.age))


@receiver(post_save, sender=Author)
def set_date(instance, **kwargs):
    exists = Author.objects.filter(id=instance.id)
    print exists
    if not exists:
        dateitem = AuthorSubmitDate(author=instance, date=datetime.datetime.now())
        dateitem.save()

booksnob/reader/forms.py
__author__ = 'user'
from django import forms
from models import Author


class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = '__all__'

booksnob/reader/views.py
from django.http import HttpResponseRedirect
from django.views.generic import TemplateView, DetailView, ListView, View, \
    UpdateView
from django.shortcuts import render
from django.views.generic.edit import FormView
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
from forms import AuthorForm
from reader.actions import get_books, get_authors
from reader.models import Author
import logging
from django.core.cache import cache, get_cache


cach = get_cache('default')
user_adds = logging.getLogger('reader_add_user')
user_updates = logging.getLogger('reader_update_user')


class HomeView(TemplateView):
    template_name = 'home.html'

    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)
        context['authors'] = get_authors()
        context['books'] = get_books()
        context['cached_avatar'] = cach.get('user_avatar')
        return context


class AuthorView(FormView):
    template_name = 'new_author.html'
    success_url = '/reader/get_auth/all'
    form_class = AuthorForm

    def form_valid(self, form):
        self.request.session['user_avatar'] = str(form.cleaned_data['avatar'])
        user_adds.debug('user {0} {1} has been added'.format
                        (form.cleaned_data['first_name'],
                         form.cleaned_data['last_name']))

        self.object = form.save()
        return super(AuthorView, self).form_valid(form)


class GetAuthorView(DetailView, UpdateView):
    model = Author
    template_name = 'author_by_id.html'
    success_url = '/reader/get_auth/all'
    fields = '__all__'

    def form_valid(self, form):
        cach.set('user_avatar', str(form.cleaned_data['avatar']), 10)
        self.request.session['user_avatar'] = str(form.cleaned_data['avatar'])
        user_updates.debug('user with {0} {1} has been updated'.format
                           (form.cleaned_data['first_name'],
                            form.cleaned_data['last_name']))
        form.save()
        return super(GetAuthorView, self).form_valid(form)


class GetAuthorList(ListView):
    model = Author
    template_name = 'all_authors.html'

    def post(self, request):
        text = request.POST.get('search', 'senya')
        choose = request.POST.get('rad', '')
        if choose == 'Desc':
            ret = Author.objects.filter(first_name__icontains=text).order_by(
                '-id')
        else:
            ret = Author.objects.filter(first_name__icontains=text).order_by(
                'id')

        return render(request, self.template_name, {'author_list': ret})


class RegisterFormView(FormView):
    form_class = UserCreationForm
    success_url = '/critic/thanks'
    template_name = 'Login.html'

    def form_valid(self, form):
        form.save()
        return super(RegisterFormView, self).form_valid(form)


class AutheticationForm(FormView):
    form_class = AuthenticationForm
    success_url = '/reader/get_auth/all'
    template_name = 'Authentification.html'

    def form_valid(self, form):
        user = form.get_user()
        login(self.request, user)

        return super(AutheticationForm, self).form_valid(form)


class LogoutForm(View):
    def get(self, request):
        logout(request)
        return HttpResponseRedirect('/')

booksnob/reader/templates/Authentification.html
{% extends 'base.html' %}
{% block content %}
    {% load bootstrap_tags %}
    <form method="post" action="">{% csrf_token %}
    {{ form|as_bootstrap }}
    <input type="submit" class="btn btn-success btn-block btn-lg"  value="Login">
    </form>
{% endblock %}

booksnob/reader/templates/Login.html
{% extends 'base.html' %}
{% block content %}
    {% load bootstrap_tags %}
    <h3>Register</h3>
    <form method="post" action="">{% csrf_token %}
    {{ form|as_bootstrap }}
    <input type="submit" class="btn btn-success btn-block btn-lg"  value="Login">
    </form>
{% endblock %}

booksnob/reader/templates/all_authors.html
{% extends 'base.html' %}
{% block content %}
    <h3>Authors:</h3>
    {% load bootstrap_tags %}
    <form method="post" action="">{% csrf_token %}
        <input name="search">
        <input type="submit" value="Search">

    <div class="well">
    <p>Order by:</p>
    <input type="radio" name="rad" value="Desc"> Desc<br>
    <input type="radio" name="rad" value="Asc"> Asc<br>

    </div>
    </form>
    <a href="{% url 'get_author' %}">
        <button  class="btn btn-default btn-lg">
            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Add new
        </button>
    </a>
    <div class="list-group">

    {% for o in author_list %}

        <a class="list-group-item" href={% url 'auth_by_id' o.pk %}>
            <img width="50px" height="50px" src="{{ o.avatar.url }}"> <br>
            <strong>ID:</strong> {{ o.pk }} <br>
            <strong>First Name:</strong> {{ o.first_name }} <br>
            <strong>Last Name:</strong> {{ o.last_name }}
        </a>

    {% endfor %}

    </div>
    <div id="forscript">

    </div>
    <script>
        $.get("http://127.0.0.1:8000/api-auth/testurl/",function(res){
            res.forEach(function(item){
                $('#forscript').append("<p>"+item.first_name+"</p>");
            });
        })
    </script>

{% endblock %}

booksnob/reader/templates/author_by_id.html
{% extends 'base.html' %}
{% block content %}
{% load bootstrap_tags %}
     <div class="well">Author: </div>
     {{ author.errors }}
     <img id="avatar" src="{{ author.avatar.url }}">
     <form role="form" method="post" enctype="multipart/form-data" action={% url 'auth_by_id' author.pk %}   >{% csrf_token %}
         <div class="form-group  ">
            <label for="id_first_name" class="control-label required-field ">
                First name:
            </label>
                <div class="">
                    <input class=" form-control" id="id_first_name" maxlength="30" name="first_name" type="text" value="{{ author.first_name }}">
                </div>
         </div>
         <div class="form-group  ">
            <label for="id_last_name" class="control-label required-field ">
                Last name
            </label>
                <div class="">
                    <input class=" form-control" id="id_last_name" maxlength="30" name="last_name" type="text" value="{{ author.last_name }}">
                </div>
         </div>
         <div class="form-group  ">
            <label for="id_email" class="control-label required-field ">
                Email
            </label>
                <div class="">
                    <input class=" form-control" id="id_email" maxlength="30" name="email" type="text" value="{{ author.email }}">
                </div>
         </div>
        <div id="div_id_avatar" class="form-group  ">
            <label for="id_avatar" class="control-label required-field ">
                Avatar
            </label>
                <div class="">
                    <input class=" form-control" id="id_avatar" name="avatar" type="file">
                </div>
        </div>

        <button type="submit" class="btn btn-default btn-lg">
            Update
        </button>
     </form>
{% endblock %}

booksnob/reader/templates/base.html
<html lang="en">
<head>
    <title>{% include "title.html" %}</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css" rel="stylesheet">

     {% load staticfiles %}
    <link rel="stylesheet" href="{% static "styles/main/home.css" %}">
  </head>
<body>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
    <div class="col-s-16">
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">

          <a href="{% url 'home' %}">
              <h3 class="navbar-brand">Reader app</h3>
          </a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">

            <li>
                {% if user.is_authenticated %}
                    <a href="{% url 'logout' %}">
                      <button type="submit" class="btn btn-default btn-lg">
                        <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span> Hello,{{ user }} Log out
                      </button>
                    </a>
                {% else %}
                     <a href="{% url 'logout' %}">
                     <button type="submit" class="btn btn-default btn-lg">
                        <span class="glyphicon glyphicon-log-in" aria-hidden="true"></span> Log in
                      </button>
                     </a>
                {% endif %}

            </li>
          </ul>
        </div>

      </div>

    </nav>
        <div class="container">
            {% block content %}{% endblock %}
        </div>

        {% include "footer.html" %}
    </div>



</body>
</html>

booksnob/reader/templates/footer.html
<footer class="footer">
      <div class="container" align="center">
        <p class="text-muted">Django reader app</p>
      </div>
</footer>

booksnob/reader/templates/home.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
    {% load bootstrap_tags %}
    <div class="container">
        <div id="critic">
            <a href="{% url "review-book" %}">

                 <img id="critic" src="{% static "styles/main/Critic.jpg" %}" alt="Critic">
             </a>
            <h1>Critic</h1>
        </div>

        <div id="reader">
            {% if user.is_authenticated %}
                 <a href="{% url "get_author_all" %}">
                  <img id="reader" src="{% static "styles/main/Reader.jpg" %}" alt="Reader">
             </a>
            {% else %}
                 <a href="{% url "login" %}">
                  <img id="reader" src="{% static "styles/main/Reader.jpg" %}" alt="Reader">
             </a>
            {% endif %}
            <h1>Reader</h1>
        </div>
        <div id="cached">
            <p>Cached Avatar (with 10 sec living)</p>
            <img  src="{{ cached_avatar }}" alt="Cached">
        </div>
    </div>
{% endblock %}

booksnob/reader/templates/new_author.html
{% extends 'base.html' %}
{% block content %}
{% load bootstrap_tags %}

    <div class="well">Add new author</div>
<form method="POST" enctype="multipart/form-data" action={% url 'get_author' %}>{% csrf_token %}

    {{ form|as_bootstrap}}

    <input title="p" type="submit" class="btn btn-success btn-block btn-lg" value="Send">
</form>
{% endblock %}

booksnob/reader/templates/title.html
Reader app